name: Seed Match Certificates

on:
  workflow_dispatch: {}

jobs:
  seed_match:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.7
          bundler-cache: true

      - run: bundle install --jobs 4 --retry 3

      - name: Write API Key
        run: |
          echo "${{ secrets.APPSTORE_API_KEY }}" | base64 --decode \
            > AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8

      - name: Nuke old App Store certs
        env:
          APP_STORE_CONNECT_API_KEY_PATH: AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8
          APP_STORE_CONNECT_API_KEY_ID:   ${{ secrets.APPSTORE_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID:    ${{ secrets.APPSTORE_ISSUER_ID }}
        run: |
          bundle exec fastlane match nuke appstore

      - name: Create AppStore cert & profile
        env:
          APP_STORE_CONNECT_API_KEY_PATH: AuthKey_${{ secrets.APPSTORE_KEY_ID }}.p8
          APP_STORE_CONNECT_API_KEY_ID:   ${{ secrets.APPSTORE_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID:    ${{ secrets.APPSTORE_ISSUER_ID }}
        run: |
          bundle exec fastlane match appstore
