name: Seed Match Certificates

on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.7

      - name: Install fastlane
        run: gem install fastlane --no-document

      - name: Decode AuthKey.p8 into ENV
        run: echo "$APPSTORE_API_KEY" > AuthKey_$APPSTORE_KEY_ID.p8
        env:
          APPSTORE_API_KEY:    ${{ secrets.APPSTORE_API_KEY }}
          APPSTORE_KEY_ID:     ${{ secrets.APPSTORE_KEY_ID }}

      - name: 🚮 Nuke old distribution certs
        env:
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APPSTORE_API_KEY }}
          APP_STORE_CONNECT_API_KEY_ID:  ${{ secrets.APPSTORE_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID:   ${{ secrets.APPSTORE_ISSUER_ID }}
        run: |
          bundle exec fastlane match nuke distribution

      - name: 🆕 Create new App Store cert & profile
        env:
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APPSTORE_API_KEY }}
          APP_STORE_CONNECT_API_KEY_ID:  ${{ secrets.APPSTORE_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID:   ${{ secrets.APPSTORE_ISSUER_ID }}
        run: |
          bundle exec fastlane match appstore

      - name: Push new certs to Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add certs/*.gpg
          git commit -m "chore: seed match certs"
          git push
